name: neo_flutterism
description: An opinionated Neobrutalism UI Kit
version: 0.2.0
homepage: https://github.com/luisburgos/neo_flutterism

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  neopop: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  coverage: ^1.0.2
  mockito: 5.3.0
