name: neo_flutterism
description: An opinionated Neobrutalism UI Kit
version: 0.1.0
homepage: https://github.com/luisburgos/neo_flutterism

environment:
<<<<<<< HEAD
  sdk: '>=2.18.6 <3.0.0'
=======
  sdk: ">=2.17.1 <4.0.0"
>>>>>>> 038b21c (feat: improve neo buttons)

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  neopop: ^1.0.2
  google_fonts: ^3.0.1
=======
  google_fonts: 3.0.1
  font_awesome_flutter: 10.3.0
>>>>>>> 038b21c (feat: improve neo buttons)

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  coverage: ^1.0.2
  mockito: 5.3.0
